### ISSUE TITLE
Website Header

### ISSUE THREAD

**Issue by JuOllie** [Women-Techmakers-Manipal/Women-Techmakers-Manipal.github.io#5]
A header with the WTM logo and 'Apprécie-la'

**Comment by mayankk98** [comment]
If there is any logo of 'Apprécie-la', add that to the repo so that this issue is resolved at the earliest

**Comment by JuOllie** [comment]
Hi Mayank, we don't have any logo of Apprécie-la. A header with the WTM logo would suffice. The /images folder contains WTM.png, bg3.jpg and bg4.jpg. Any of those could be used.

**Comment by mayankk98** [comment]
No links to other possible sections are to be added to the header ?
A navbar with only a logo will seem a bit weird

**Comment by JuOllie** [comment]
Just  the writing - Apprécie-la with the logo. And contact icons if possible (to the Facebook group, Twitter page and meetups). What do you think about this? We don't have any other additional sections as of now. As we keep adding members,we will have these.

**Comment by mayankk98** [comment]
Sounds cool

**Comment by mayankk98** [comment]
Resolved issue

**Comment by JuOllie** [comment]
Thanks Mayank! 👍
